use serde_json::{json, Value};
use yamaa_adapters::dependency_transport::{
    analyze_dependencies, TransportError, MAX_REQUEST_BYTES,
};

/// Fixture indices are independently authored output truth, never generated by the service.
fn indices(text: &str) -> Vec<usize> {
    if text == "-" {
        vec![]
    } else {
        text.split(',').map(|n| n.parse().unwrap()).collect()
    }
}

/// The shared corpus survives serialization with exact cycle direction and stable ordering.
#[test]
fn shared_graph_truth_crosses_transport() {
    for line in include_str!("../../yamaa-core/tests/fixtures/dependency_analysis.tsv")
        .lines()
        .skip(1)
    {
        let fields: Vec<_> = line.split('\t').collect();
        let mut graph = vec![vec![]; fields[1].parse().unwrap()];
        if fields[2] != "-" {
            for edges in fields[2].split(';') {
                let (node, dependencies) = edges.split_once(':').unwrap();
                graph[node.parse::<usize>().unwrap()] = indices(dependencies);
            }
        }
        let request = json!({"protocol":"dependency-analysis/1","dependencies":graph});
        let actual: Value =
            serde_json::from_str(&analyze_dependencies(&request.to_string()).unwrap()).unwrap();
        assert_eq!(
            actual,
            json!({"protocol":"dependency-analysis/1","outcome":{
                "status":"complete",
                "cycle":(fields[3]!="-").then(|| indices(fields[3])),
                "order":indices(fields[4])
            }}),
            "{}",
            fields[0]
        );
    }
}

/// Unknown fields, duplicate fields, invalid references and lossy indices never enter analysis.
#[test]
fn strict_request_admission() {
    for text in [
        "null",
        r#"{"protocol":"dependency-analysis/1","dependencies":[],"limits":{}}"#,
        r#"{"protocol":"dependency-analysis/1","protocol":"dependency-analysis/1","dependencies":[]}"#,
        r#"{"protocol":"dependency-analysis/1","dependencies":[[true]]}"#,
        r#"{"protocol":"dependency-analysis/1","dependencies":[[1.0]]}"#,
        r#"{"protocol":"dependency-analysis/1","dependencies":[[-1]]}"#,
    ] {
        assert_eq!(
            analyze_dependencies(text),
            Err(TransportError::InvalidEnvelope)
        );
    }
    assert_eq!(
        analyze_dependencies(r#"{"protocol":"future/2","dependencies":[]}"#),
        Err(TransportError::UnsupportedProtocol)
    );
    assert_eq!(
        analyze_dependencies(r#"{"protocol":"dependency-analysis/1","dependencies":[[1]]}"#),
        Err(TransportError::InvalidGraph)
    );
    assert_eq!(
        analyze_dependencies(&" ".repeat(MAX_REQUEST_BYTES + 1)),
        Err(TransportError::RequestLimit)
    );
}

/// Trusted graph limits count authored repetitions and remain separate from language cycles.
#[test]
fn resource_outcomes_preserve_required_counts_and_fresh_reuse() {
    for (graph, resource, limit, required) in [
        (vec![vec![]; 4097], "nodes", "4096", "4097"),
        (vec![vec![0; 65_537]], "edges", "65536", "65537"),
    ] {
        let request = json!({"protocol":"dependency-analysis/1","dependencies":graph});
        let actual: Value =
            serde_json::from_str(&analyze_dependencies(&request.to_string()).unwrap()).unwrap();
        assert_eq!(
            actual,
            json!({"protocol":"dependency-analysis/1","outcome":{
                "status":"limit","resource":resource,"limit":limit,"required":required
            }})
        );
    }
    assert_eq!(
        analyze_dependencies(r#"{"protocol":"dependency-analysis/1","dependencies":[[0]]}"#)
            .unwrap(),
        r#"{"protocol":"dependency-analysis/1","outcome":{"status":"complete","cycle":[0,0],"order":[]}}"#
    );
}
