[package]
name = "yamaa-adapters"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
yamaa-core = { path = "../yamaa-core" }
yamaa-engine = { path = "../yamaa-engine" }
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.145"

arrow-array = { version = "=60.0.0", default-features = false }
arrow-schema = { version = "=60.0.0", default-features = false }
arrow-buffer = { version = "=60.0.0", default-features = false }
