"""Portable expression and predicate evaluation helpers."""

from yamaa.expressions.aggregate import (
    REDUCERS,
    AggregateAst,
    AggregateError,
    aggregate_handlers,
    aggregate_identifiers,
    aggregate_star_datasets,
    evaluate_aggregate,
    is_single_reduction,
    parse_aggregate,
    parse_aggregate_cached,
    ungrouped_identifiers,
)
from yamaa.expressions.core import (
    CORE_EXPRESSION_HANDLERS,
    AbsentValue,
    ExpressionHandler,
    ExpressionInput,
    FailedResolution,
    MappingResolver,
    MultipleMatchResolver,
    NestedDispatcher,
    RelationalResolver,
    Resolution,
    ResolvedValue,
    Resolver,
    evaluate_nested,
    expression_condition,
    handler_value,
    relational_handler,
)
from yamaa.expressions.dates import collected_precision, date_handlers, whole_units
from yamaa.expressions.dispatch import (
    DEFAULT_EXPRESSION_OPERATIONS,
    ExpressionDispatcher,
    build_expression_handlers,
    evaluate_expression,
)
from yamaa.expressions.numeric import (
    FUNCTION_ARITIES,
    PROHIBITED_KEYWORDS,
    NumericAst,
    NumericError,
    evaluate_numeric,
    numeric_identifiers,
    parse_numeric,
    parse_numeric_cached,
)
from yamaa.expressions.predicates import (
    PredicateAst,
    PredicateError,
    PredicateResult,
    PredicateValue,
    TruthValue,
    evaluate_predicate,
    parse_predicate,
    parse_predicate_cached,
)
from yamaa.expressions.strings import (
    TemplateError,
    TemplatePart,
    parse_template,
    parse_template_cached,
    template_identifiers,
)
from yamaa.expressions.text import ascii_lower, ascii_upper
from yamaa.expressions.windows import (
    WINDOW_OPERATIONS,
    Partition,
    evaluate_window,
    window_handlers,
)

__all__ = [
    "CORE_EXPRESSION_HANDLERS",
    "DEFAULT_EXPRESSION_OPERATIONS",
    "FUNCTION_ARITIES",
    "PROHIBITED_KEYWORDS",
    "REDUCERS",
    "WINDOW_OPERATIONS",
    "AbsentValue",
    "AggregateAst",
    "AggregateError",
    "ExpressionDispatcher",
    "ExpressionHandler",
    "ExpressionInput",
    "FailedResolution",
    "MappingResolver",
    "MultipleMatchResolver",
    "NestedDispatcher",
    "NumericAst",
    "NumericError",
    "Partition",
    "PredicateAst",
    "PredicateError",
    "PredicateResult",
    "PredicateValue",
    "RelationalResolver",
    "Resolution",
    "ResolvedValue",
    "Resolver",
    "TemplateError",
    "TemplatePart",
    "TruthValue",
    "aggregate_handlers",
    "aggregate_identifiers",
    "aggregate_star_datasets",
    "ascii_lower",
    "ascii_upper",
    "build_expression_handlers",
    "collected_precision",
    "date_handlers",
    "evaluate_aggregate",
    "evaluate_expression",
    "evaluate_nested",
    "evaluate_numeric",
    "evaluate_predicate",
    "evaluate_window",
    "expression_condition",
    "handler_value",
    "is_single_reduction",
    "numeric_identifiers",
    "parse_aggregate",
    "parse_aggregate_cached",
    "parse_numeric",
    "parse_numeric_cached",
    "parse_predicate",
    "parse_predicate_cached",
    "parse_template",
    "parse_template_cached",
    "relational_handler",
    "template_identifiers",
    "ungrouped_identifiers",
    "whole_units",
    "window_handlers",
]
