schema_version: "1.0"
version: "1.0.0"

runtime:
  language: r
  artifact:
    reference: org.example/yamaa/bmi-r:1.0.0

functions:
  bmi:
    contract: python/contracts.yaml
    binding:
      call: projectbmi::bmi
    conformance: python/conformance/bmi.yaml
