"""Reproduce schema diagnostic printable intervals from pinned Unicode properties.

Python-style representation prints L/M/N/P/S categories and ASCII space. The
union of Grapheme_Base and Grapheme_Extend contains those categories; category
annotations exclude controls, separators, private-use and unassigned scalars.
Host Unicode classifiers are deliberately not an oracle for these intervals.
"""

import argparse
from pathlib import Path

CORE = Path(__file__).resolve().parents[1] / "crates/yamaa-core"
SOURCE = CORE / "unicode/18.0.0/DerivedCoreProperties.txt"
TARGET = CORE / "src/schema/printable_data.rs"


def render():
    """Merge authoritative printable ranges; no engine observations or digests."""
    text = SOURCE.read_text(encoding="utf-8")
    assert text.startswith("# DerivedCoreProperties-18.0.0.txt\n")
    ranges = [(0x20, 0x20)]
    for line in text.splitlines():
        data, _, comment = line.partition("#")
        fields = data.strip().split(";")
        if len(fields) != 2 or fields[1].strip() not in {
            "Grapheme_Base", "Grapheme_Extend"
        }:
            continue
        category = comment.split()[0]
        if category[0] not in "LMNPS":
            continue
        bounds = fields[0].strip().split("..")
        low, high = int(bounds[0], 16), int(bounds[-1], 16)
        assert 0 <= low <= high <= 0x10FFFF
        assert high < 0xD800 or low > 0xDFFF
        ranges.append((low, high))
    merged = []
    for low, high in sorted(ranges):
        if merged:
            assert low > merged[-1][1], "overlapping authoritative ranges"
            if low == merged[-1][1] + 1:
                merged[-1] = merged[-1][0], high
                continue
        merged.append((low, high))
    lines = [
        "// Generated by rust/tools/generate_schema_printable.py --write.",
        "// Unicode 18.0.0 L/M/N/P/S and ASCII space, for diagnostic representation.",
        "// Source: https://www.unicode.org/Public/18.0.0/ucd/DerivedCoreProperties.txt",
        "// Copyright Unicode, Inc. See ../../unicode/LICENSE.txt for Unicode-3.0.",
        "",
        "pub(super) const PRINTABLE: &[(u32, u32)] = &[",
        *(f"    (0x{low:X}, 0x{high:X})," for low, high in merged),
        "];",
        "",
    ]
    return "\n".join(lines)


def main():
    """Check by default; rewriting generated source requires an explicit option."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.write:
        TARGET.write_text(expected, encoding="ascii", newline="\n")
    else:
        assert TARGET.read_bytes() == expected.encode("ascii"), "schema printable tables differ"
        print("Unicode 18.0.0 schema printable table reproduces pinned authoritative data")


if __name__ == "__main__":
    main()
