"""Embed authoritative YAML bytes in native packages; compare directly, without hashes."""

import argparse
from pathlib import Path

WORKSPACE = Path(__file__).resolve().parents[1]
SOURCE = WORKSPACE.parent / "yaml"
TARGET = WORKSPACE / "crates/yamaa-adapters/src/shipped_schema_data.rs"


def render():
    """Keep the entry first and preserve every module's exact UTF-8 bytes."""
    # Environment and submission are separate roots. Shared bundle admission
    # rejects missing or unused modules, so closure drift fails native tests.
    modules = [SOURCE / "schema.yaml"] + sorted(
        p
        for p in SOURCE.glob("schema_*.yaml")
        if p.name not in {"schema_define.yaml", "schema_environment.yaml"}
    )
    lines = [
        "// Generated by rust/tools/generate_shipped_schema.py --write.",
        "// Authoritative sources: yaml/schema*.yaml. Do not edit this copy.",
        "#[rustfmt::skip]",
        "pub(super) const MODULES: &[(&str, &str)] = &[",
    ]
    for module in modules:
        content = module.read_bytes().decode("ascii")
        # Raw strings preserve newlines and backslashes from the written source.
        delimiter = "#"
        while '"' + delimiter in content:
            delimiter += "#"
        lines.append(f'    ("{module.name}", r{delimiter}"{content}"{delimiter}),')
    lines += ["];", "#[rustfmt::skip]", "pub(super) const ENVIRONMENT_MODULES: &[(&str, &str)] = &["]
    for module in [SOURCE / "schema_environment.yaml", SOURCE / "schema_shared.yaml"]:
        content = module.read_bytes().decode("ascii")
        delimiter = "#"
        while '"' + delimiter in content:
            delimiter += "#"
        lines.append(f'    ("{module.name}", r{delimiter}"{content}"{delimiter}),')
    return "\n".join([*lines, "];", ""])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    expected = render().encode("ascii")
    if args.write:
        TARGET.write_bytes(expected)
    else:
        assert TARGET.read_bytes() == expected, (
            "shipped schema differs from authoritative YAML"
        )
        print("PASS: shipped schema preserves authoritative YAML bytes")


if __name__ == "__main__":
    main()
