"""Reproduce safe regex ID tables from pinned, licensed Unicode property data.

This consumes authoritative data, never engine observations. Normal invocation
checks committed bytes; --write explicitly regenerates the derived tables.
"""

import argparse
from pathlib import Path

CORE = Path(__file__).resolve().parents[1] / "crates/yamaa-core"
SOURCE = CORE / "unicode/18.0.0/DerivedCoreProperties.txt"
TARGET = CORE / "src/regex/identifier_data.rs"
LICENSE = CORE / "unicode/LICENSE.txt"
LICENSE_COPIES = [
    CORE.parent / "yamaa-python/LICENSE-UNICODE.txt",
    CORE.parents[2] / "R/yamaanative/inst/LICENSE-UNICODE.txt",
]


def render():
    """Read disjoint property ranges and merge adjacent intervals without changing sets."""
    text = SOURCE.read_text(encoding="utf-8")
    assert text.startswith("# DerivedCoreProperties-18.0.0.txt\n")
    properties = {"ID_Start": [], "ID_Continue": []}
    for line in text.splitlines():
        fields = line.split("#", 1)[0].strip().split(";")
        if len(fields) != 2 or fields[1].strip() not in properties:
            continue
        bounds = fields[0].strip().split("..")
        low, high = int(bounds[0], 16), int(bounds[-1], 16)
        assert 0 <= low <= high <= 0x10FFFF
        assert high < 0xD800 or low > 0xDFFF
        properties[fields[1].strip()].append((low, high))
    output = [
        "// Generated by rust/tools/generate_regex_identifiers.py --write.",
        "// Unicode 18.0.0 ID_Start / ID_Continue (not XID properties).",
        "// Source: https://www.unicode.org/Public/18.0.0/ucd/DerivedCoreProperties.txt",
        "// Copyright Unicode, Inc. See ../../unicode/LICENSE.txt for Unicode-3.0.",
        "",
    ]
    for name, ranges in properties.items():
        assert (
            sum(high - low + 1 for low, high in ranges)
            == {
                "ID_Start": 158739,
                "ID_Continue": 162100,
            }[name]
        )
        merged = []
        for low, high in sorted(ranges):
            if merged:
                assert low > merged[-1][1], "overlapping authoritative ranges"
                if low == merged[-1][1] + 1:
                    merged[-1] = merged[-1][0], high
                    continue
            merged.append((low, high))
        output.append(f"pub(super) const {name.upper()}: &[(u32, u32)] = &[")
        output.extend(f"    (0x{low:X}, 0x{high:X})," for low, high in merged)
        output.extend(["];", ""])
    return "\n".join(output)


def main():
    """Check by default, requiring an explicit switch to modify generated source."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.write:
        TARGET.write_text(expected, encoding="ascii", newline="\n")
        for path in LICENSE_COPIES:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(LICENSE.read_bytes())
    else:
        assert TARGET.read_bytes() == expected.encode("ascii"), (
            "identifier tables differ"
        )
        for path in LICENSE_COPIES:
            assert path.read_bytes() == LICENSE.read_bytes(), (
                f"Unicode notice differs: {path}"
            )
        print("Unicode 18.0.0 regex ID tables reproduce pinned authoritative data")


if __name__ == "__main__":
    main()
