schema_version: "1.0"
version: "1.0.0"

runtime:
  language: python
  artifact:
    reference: org.example/yamaa/bmi-python:1.0.0

functions:
  bmi:
    contract: contracts.yaml
    binding:
      call: projectbmi.bmi
    conformance: conformance/bmi.yaml
