from collections.abc import Callable
from typing import Literal

class DomainError(Exception): ...

class _DomainResult:
    def observations(self) -> str | None: ...
    def output(self) -> bytes | None: ...
    def issues(self) -> list[tuple[str, str, str | None, list[str], str]]: ...
    def save(self) -> bool: ...

def _domain_file(
    specification: str, environment: str | None = None
) -> _DomainResult: ...
def _check_file(
    specification: str, environment: str | None = None
) -> list[tuple[str, str, str | None, list[str], str]]: ...
def engine_info() -> dict[str, str | bool]: ...
def analyze_aggregate(request: str) -> str: ...
def analyze_numeric(request: str) -> str: ...
def analyze_predicate(request: str) -> str: ...
def interpret_schema(request: str) -> str: ...
def traverse_inheritance(
    schema_request: str, request: str, callback: Callable[[str, int], str]
) -> str: ...

class _Schema:
    def analyze(self, request: str) -> str: ...
    def traverse_inheritance(
        self, request: str, callback: Callable[[str, int], str]
    ) -> str: ...

def _compile_schema(request: str) -> tuple[_Schema | None, str]: ...
def evaluate_regex(request: str) -> str: ...
def analyze_dependencies(request: str) -> str: ...
def analyze_column_dependencies(request: str) -> str: ...
def scalar_round_trip(request: str) -> str: ...
def evaluate_numeric(request: str) -> str: ...
def table_round_trip(request: bytes) -> bytes: ...
def table_snapshot(request: bytes) -> str: ...
def execute_dataset_sources(
    request: str, source: bytes, secondary: list[bytes]
) -> tuple[bytes | None, str]: ...
def execute_dataset_functions(
    request: str,
    source: bytes,
    secondary: list[bytes],
    callbacks: list[Callable[..., object]],
) -> tuple[bytes | None, str]: ...

# Private measurement entrypoint: ordinary table/outcome plus dataset-profile/1 metrics.
def _profile_dataset_functions(
    request: str,
    source: bytes,
    secondary: list[bytes],
    callbacks: list[Callable[..., object]],
) -> tuple[bytes | None, str, str]: ...
def dataset_capabilities() -> str: ...
def execute_dataset(request: str, source: bytes) -> tuple[bytes | None, str]: ...
def invoke_function(request: str, callback: Callable[..., object]) -> str: ...

# Private bridge for the optional facade's known temporal result representations.
def _temporal_result(kind: object, fields: object, precision: object) -> object: ...

# Private prepared catalog for the optional compiler adapter; no public constructor.
class _ReferenceCatalog:
    def analyze(self, request: str) -> str: ...

def _compile_reference_catalog(
    request: str,
) -> tuple[_ReferenceCatalog | None, str]: ...
def analyze_references(request: str) -> str: ...
def reference_capabilities() -> str: ...

# Decode retained ASCII source into lossless yaml/1 JSON through shared Rust.
def decode_yaml(source: bytes) -> str: ...

# Internal bounded original-YAML compiler. Source capture remains explicit host IO.
class _Specification:
    def check_issues(self) -> str: ...
    def build(
        self,
        capture: Callable[
            [str, str, int],
            tuple[bytes, bool]
            | tuple[Literal["missing", "not_regular_file"], BaseException],
        ],
        metadata: tuple[str, str, str, str, str],
        inspect: Callable[
            [str, str],
            None | tuple[Literal["missing", "not_regular_file"], BaseException],
        ]
        | None = None,
    ) -> _BuildResult: ...
    def source(self) -> tuple[str, str]: ...
    def execute_csv(self, source: bytes) -> tuple[bytes | None, str]: ...
    def report(
        self,
        capture: Callable[
            [str, str, int],
            tuple[bytes, bool]
            | tuple[Literal["missing", "not_regular_file"], BaseException],
        ],
        publish: Callable[[str, bytes], None],
        metadata: tuple[str, str, str, str, str],
        inspect: Callable[
            [str, str],
            None | tuple[Literal["missing", "not_regular_file"], BaseException],
        ]
        | None = None,
    ) -> str: ...
    def failure_report(
        self,
        capture: Callable[
            [str, str, int],
            tuple[bytes, bool]
            | tuple[Literal["missing", "not_regular_file"], BaseException],
        ],
        metadata: tuple[str, str, str, str, str],
        inspect: Callable[
            [str, str],
            None | tuple[Literal["missing", "not_regular_file"], BaseException],
        ]
        | None = None,
    ) -> str: ...

def _prepare_specification(
    modules: list[tuple[str, bytes]], entry: int, identity: str, source: bytes
) -> _Specification: ...

class _BuildResult:
    def output(self) -> bytes | None: ...
    def observations(self) -> str: ...
    def save(self, publish: Callable[[str, bytes], None]) -> str: ...

def _prepare_document(
    identity: str,
    source: bytes,
    canonicalize: Callable[[str, str], tuple[str, str] | None],
    capture: Callable[[str, str, int], bytes | None],
    rebase: Callable[[str, str, str, int], str],
) -> _Specification: ...
def _prepare_inherited_specification(
    modules: list[tuple[str, bytes]],
    entry: int,
    identity: str,
    source: bytes,
    canonicalize: Callable[[str, str], tuple[str, str] | None],
    capture: Callable[[str, str, int], bytes | None],
    rebase: Callable[[str, str, str, int], str],
) -> _Specification: ...

# Private owned project service; schema closures and read roots stay explicit.
class _ProjectSpecification:
    def preparation_status(self) -> str: ...
    def capture_reads(self) -> int: ...
    def build(self) -> _ProjectAttempt: ...

class _ProjectAttempt:
    def engine_succeeded(self) -> bool: ...
    def result(self, metadata: tuple[str, str, str, str, str]) -> _ProjectResult: ...
    def activation(self) -> str: ...
    def host_failures(self) -> list[tuple[str, BaseException]]: ...
    def failure_facts(self) -> list[tuple[str, dict[str, object]]]: ...
    def prepared_sources(self) -> list[tuple[str, bytes]]: ...
    def study_snapshot(self, index: int) -> bytes | None: ...

class _ProjectResult:
    def report_status(self) -> str: ...
    def output(self) -> bytes | None: ...
    def issues(self) -> list[tuple[str, str, str | None, list[str], str]]: ...
    def observations(self) -> str: ...
    def save(self, publish: Callable[[str, bytes], None]) -> str: ...
    def save_file(self, declared: str, target: str) -> str: ...
    def propagate_interrupt(self) -> None: ...
    def activation(self) -> str: ...
    def host_failures(self) -> list[tuple[str, BaseException]]: ...
    def failure_facts(self) -> list[tuple[str, dict[str, object]]]: ...
    def prepared_sources(self) -> list[tuple[str, bytes]]: ...
    def study_snapshot(self, index: int) -> bytes | None: ...

def _prepare_file_project(
    project_root: str,
    base_directory: str,
    entry: str,
    environment: str,
    data_roots: list[str],
    specification_modules: list[tuple[str, bytes]],
    specification_entry: int,
    environment_modules: list[tuple[str, bytes]],
    environment_entry: int,
) -> _ProjectSpecification: ...
