from collections.abc import Callable

def engine_info() -> dict[str, str | bool]: ...
def analyze_dependencies(request: str) -> str: ...
def analyze_column_dependencies(request: str) -> str: ...
def scalar_round_trip(request: str) -> str: ...
def evaluate_numeric(request: str) -> str: ...
def table_round_trip(request: bytes) -> bytes: ...
def table_snapshot(request: bytes) -> str: ...
def execute_dataset_sources(
    request: str, source: bytes, secondary: list[bytes]
) -> tuple[bytes | None, str]: ...
def execute_dataset_functions(
    request: str,
    source: bytes,
    secondary: list[bytes],
    callbacks: list[Callable[..., object]],
) -> tuple[bytes | None, str]: ...

# Private measurement entrypoint: ordinary table/outcome plus dataset-profile/1 metrics.
def _profile_dataset_functions(
    request: str,
    source: bytes,
    secondary: list[bytes],
    callbacks: list[Callable[..., object]],
) -> tuple[bytes | None, str, str]: ...
def dataset_capabilities() -> str: ...
def execute_dataset(request: str, source: bytes) -> tuple[bytes | None, str]: ...
def invoke_function(request: str, callback: Callable[..., object]) -> str: ...

# Private bridge for the optional facade's known temporal result representations.
def _temporal_result(kind: object, fields: object, precision: object) -> object: ...
