def engine_info() -> dict[str, str | bool]: ...
def scalar_round_trip(request: str) -> str: ...
def evaluate_numeric(request: str) -> str: ...
def table_round_trip(request: bytes) -> bytes: ...
def table_snapshot(request: bytes) -> str: ...
