// Generated by rust/tools/generate_shipped_schema.py --write.
// Authoritative sources: yaml/schema*.yaml. Do not edit this copy.
#[rustfmt::skip]
pub(super) const MODULES: &[(&str, &str)] = &[
    ("schema.yaml", r#"version: "1.0"

# See REQ-1045.

includes:
    - schema_shared.yaml
    - schema_derivation.yaml
    - schema_verification.yaml
    - schema_metadata.yaml

root_class:
    - schema_version:
        type: str
        required: true
        description: See REQ-1042.
    - parents:
        type: [path, "list[path]"]
        required: false
        description: See REQ-1042.
    - domain:
        type: identifier
        required: true
        description: See REQ-1042.
    - keys:
        type: "list[identifier]"
        required: true
        description: See REQ-1042.
    - input:
        type: "dict[identifier, dataset_source]"
        required: true
        description: See REQ-1042.
    - base:
        type: identifier
        required: false
        description: See REQ-1042.
    - filter:
        type: predicate
        required: false
        description: See REQ-1042.
    - output:
        type: output_class
        required: true
        description: See REQ-1042.
    - windows:
        type: "dict[identifier, window_spec]"
        required: false
        description: See REQ-1251.
    - intermediates:
        type: "list[intermediate_class]"
        required: false
        description: See REQ-1042.
    - columns:
        type: "list[column_class]"
        required: true
        description: See REQ-1042.
    - rows:
        type: "list[row_class]"
        required: false
        description: See REQ-1042.
    - verifications:
        type: [dataset_verification, "list[dataset_verification]"]
        required: false
        description: See REQ-1042.
    - submission:
        type: submission_dataset_class
        required: false
        description: See REQ-1042.
    - metadata:
        type: "dict[str, str]"
        required: false
        description: See REQ-1042.

output_class:
    - path:
        type: path
        required: true
        description: See REQ-1047.
    - decimals:
        type: int
        required: false
        description: See REQ-1047.
    - columns:
        type: "list[identifier]"
        required: true
        description: See REQ-1047.
    - warning_log:
        type: path
        required: false
        description: See REQ-1047.
    - verification_log:
        type: path
        required: false
        description: See REQ-1047.
    - order_by:
        type: "list[order_by_term]"
        required: false
        description: See REQ-1047.

intermediate_class:
    - id:
        type: intermediate_id
        required: true
        description: See REQ-1048.
    - dataset:
        type: identifier
        required: true
        description: See REQ-1048.
    - fields_from: match_key_range_fields
    - fields_from: match_filter_fields
    - fields_from: match_selection_fields
    - columns:
        type: "list[identifier]"
        required: false
        description: See REQ-1048.
    - no_match:
        type: literal_value
        required: false
        description: See REQ-1048.
    - derivations:
        type: "dict[identifier, derivation]"
        required: false
        description: See REQ-1185.
    - verifications:
        type: "list[intermediate_verification]"
        required: false
        description: See REQ-1245.

record_between_class:
    - value:
        type: variable
        required: true
        description: See REQ-1049.
    - lower:
        type: identifier
        required: false
        description: See REQ-1049.
    - upper:
        type: identifier
        required: false
        description: See REQ-1049.

# See REQ-0251.
match_key_range_fields:
    - key: {type: match_key}
    - between: {type: record_between_class}

match_filter_fields:
    - filter: {type: predicate}

match_selection_fields:
    - order_by: {type: "list[order_by_term]"}
    - keep: {type: keep_policy}

column_class:
    - name:
        type: identifier
        required: true
        description: See REQ-1043.
    - type:
        type: column_type
        required: true
        description: See REQ-1043.
    - label:
        type: str
        required: false
        description: See REQ-1043.
    # See REQ-1260.
    - derivation:
        type: derivation
        required: false
        description: See REQ-1043.
    - verifications:
        type: [column_verification, "list[column_verification]"]
        required: false
        description: See REQ-1043.
    - submission:
        type: submission_column_class
        required: false
        description: See REQ-1043.
    - metadata:
        type: "dict[str, str]"
        required: false
        description: See REQ-1043.

row_class:
    - id:
        type: row_id
        required: true
        description: See REQ-1056.
    - dataset:
        type: identifier
        required: false
        description: See REQ-1056.
    - group_by:
        type: "list[variable]"
        required: false
        description: See REQ-1056.
    - filter:
        type: predicate
        required: false
        description: See REQ-1056.
    # See REQ-0199.
    - derivations:
        type: "dict[identifier, derivation]"
        required: true
        description: See REQ-1056.
    - submission:
        type: "dict[identifier, submission_column_class]"
        required: false
        description: See REQ-1056.

variable:
    type: str
    pattern: '^[A-Za-z_][A-Za-z0-9_]*(\.[A-Za-z_][A-Za-z0-9_]*)*$'
    description: See REQ-1057.

match_key:
    type: [match_key_columns, "dict[identifier, match_value]"]
    description: See REQ-0115.

match_key_columns:
    type: [identifier, "list[identifier]"]
    description: See REQ-0115.

match_value:
    type: [variable, expression]
    description: See REQ-1259.

dataset_source:
    type: [project_path, dataset_class]
    description: See REQ-1059.

dataset_class:
    - path:
        type: project_path
        required: true
        description: See REQ-1060.
    - types:
        type: "dict[identifier, column_type]"
        required: false
        description: See REQ-1060.
    - schema:
        type: project_path
        required: false
        description: See REQ-1060.
    - empty_string:
        type: str
        required: false
        default: missing
        values: [missing, present]
        description: See REQ-1158.
    - ordinal:
        type: identifier
        required: false
        description: See REQ-1291.

intermediate_id:
    type: str
    pattern: '^[A-Za-z_][A-Za-z0-9_]*$'
    description: See REQ-1050.

row_id:
    type: str
    min_length: 1
    description: See REQ-1044.

regex:
    type: str
    min_length: 1
    description: See REQ-1058.

predicate:
    type: str
    min_length: 1
"#),
    ("schema_derivation.yaml", r#"version: "1.0"

includes:
    - schema_expression_core.yaml
    - schema_expression_mapping.yaml
    - schema_expression_str.yaml
    - schema_expression_numeric.yaml
    - schema_expression_date.yaml
    - schema_expression_window.yaml
    - schema_expression_aggregate.yaml
    - schema_expression_odm.yaml
    - schema_function.yaml

derivation:
    type: [str, expression, handled_expression_class]

handled_expression_class:
    - value: {type: expression, required: true}
    - unconvertible: {type: literal_value, required: false}

expression:
    registry: expressions
"#),
    ("schema_expression_aggregate.yaml", r#"version: "1.0"

# See REQ-1091.

expressions:
# See REQ-1092.
    aggregate:
        type: [aggregate_expression, aggregate_class]

aggregate_class:
    - fields_from: match_key_range_fields
    - fields_from: match_filter_fields
    - group_by:
        type: "list[variable]"
        description: See REQ-1088.
    - derive:
        type: "list[derive_binding_class]"
        required: false
        description: See REQ-1189.
    - expr:
        type: aggregate_expression
        required: true
        description: See REQ-1088.

derive_binding_class:
    - name:
        type: identifier
        required: true
        description: See REQ-1192.
    - type:
        type: column_type
        required: true
        description: See REQ-1192.
    - derivation:
        type: derivation
        required: true
        description: See REQ-1192.

aggregate_expression:
    type: str
    min_length: 1
    description: See REQ-1089.
"#),
    ("schema_expression_core.yaml", r#"version: "1.0"

expressions:
    source: # See REQ-1093.
        type: [variable, source_binding_class]
        description: See REQ-1093.
    literal: # See REQ-1094.
        type: literal_value
        description: See REQ-1094.
    first_available: # See REQ-1095.
        - sources:
            type: "list[filtered_source]"
            required: true
            description: See REQ-1095.
        - missing:
            type: literal_value
            description: See REQ-1095.
    greatest: # See REQ-1096.
        - sources:
            type: "list[variable]"
            required: true
            description: See REQ-1096.
    least: # See REQ-1097.
        - sources:
            type: "list[variable]"
            required: true
            description: See REQ-1097.
    case: # See REQ-1098.
        type: "list[case_item_class]"
        description: See REQ-1098.
    flag: # See REQ-1256.
        type: [predicate, flag_class]
        description: See REQ-1256.

source_binding_class:
    - variable:
        type: variable
        required: true
        description: See REQ-1051.
    - fields_from: match_filter_fields
    - fields_from: match_selection_fields
    - absent:
        type: literal_value
        description: See REQ-1051.

flag_class:
    - condition:
        type: predicate
        required: true
        description: See REQ-1256.
    - true_value:
        type: literal_value
        default: "Y"
        description: See REQ-1256.
    - false_value:
        type: literal_value
        description: See REQ-1257.
    - missing:
        type: literal_value
        description: See REQ-1257.

filtered_source:
    type: [variable, filtered_source_class]
    description: See REQ-1052.

filtered_source_class:
    - variable:
        type: variable
        required: true
        description: See REQ-1053.
    - filter:
        type: predicate
        required: true
        description: See REQ-1053.

keep_policy:
    type: str
    values: [first, last]
    description: See REQ-0119.

order_by_term:
    type: [variable, order_term_class]
    description: See REQ-1102.

order_term_class:
    - variable:
        type: variable
        required: true
        description: See REQ-1103.
    - direction:
        type: str
        default: asc
        values: [asc, desc]
        description: See REQ-1103.
    - nulls:
        type: str
        default: last
        values: [first, last]
        description: See REQ-1103.

case_item_class:
    type: [case_branch_class, case_otherwise_class]
    description: See REQ-1099.

case_branch_class:
    - when:
        type: predicate
        required: true
        description: See REQ-1100.
    - then:
        type: case_result
        required: true
        description: See REQ-1100.

case_otherwise_class:
    - otherwise:
        type: case_result
        required: true
        description: See REQ-1101.

case_result:
    type: [str, expression]
"#),
    ("schema_expression_date.yaml", r#"version: "1.0"

expressions:
    date_diff: # See REQ-1104.
        - start:
            type: variable
            required: true
            description: See REQ-1104.
        - end:
            type: variable
            required: true
            description: See REQ-1104.
        - unit:
            type: str
            required: true
            values: [day, week, month, year]
            description: See REQ-1104.
        - bounds:
            type: str
            default: exclusive
            values: [exclusive, inclusive, between]
            description: See REQ-1104.
    date_impute: # See REQ-1105.
        - source:
            type: variable
            required: true
            description: See REQ-1105.
        - month:
            type: int
            description: See REQ-1105.
        - day:
            type: [int, day_rule]
            required: true
            description: See REQ-1105.
        - minimum_source_precision:
            type: str
            default: year
            values: [year, month]
            description: See REQ-1105.
        - not_before:
            type: variable
            description: See REQ-1105.
        - missing:
            type: literal_value
            description: See REQ-1105.
        - invalid:
            type: literal_value
            description: See REQ-1105.
    date_precision: # See REQ-1106.
        - source:
            type: variable
            required: true
            description: See REQ-1106.
        - missing:
            type: literal_value
            description: See REQ-1106.
        - invalid:
            type: literal_value
            description: See REQ-1106.
    datetime_impute: # See REQ-1182.
        - source:
            type: variable
            required: true
            description: See REQ-1182.
        - time:
            type: time_rule
            required: true
            description: See REQ-1182.
        - missing:
            type: literal_value
            description: See REQ-1182.
        - invalid:
            type: literal_value
            description: See REQ-1182.
    datetime_precision: # See REQ-1183.
        - source:
            type: variable
            required: true
            description: See REQ-1183.
        - missing:
            type: literal_value
            description: See REQ-1183.
        - invalid:
            type: literal_value
            description: See REQ-1183.
    to_date: # See REQ-1107.
        - source:
            type: variable
            required: true
            description: See REQ-1107.
    study_day: # See REQ-1108.
        - date:
            type: variable
            required: true
            description: See REQ-1108.
        - reference:
            type: variable
            required: true
            description: See REQ-1108.
    to_epoch_day: # See REQ-1188.
        - source:
            type: variable
            required: true
            description: See REQ-1188.

day_rule:
    type: str
    values: [first, last]
    description: See REQ-1109.

time_rule:
    type: str
    values: [first, last]
    description: See REQ-1184.
"#),
    ("schema_expression_mapping.yaml", r#"version: "1.0"

expressions:
    mapping: # See REQ-1110.
        - source:
            type: filtered_source
            required: true
            description: See REQ-1110.
        - dict:
            type: ["dict[str, literal_value]", project_path]
            required: true
            description: See REQ-1110.
        - case_sensitive:
            type: bool
            default: true
            description: See REQ-1110.
        - missing:
            type: literal_value
            description: See REQ-1110.
        - unmapped:
            type: literal_value
            description: See REQ-1110.
    cut: # See REQ-1118.

        - source:
            type: variable
            required: true
            description: See REQ-1118.
        - breaks:
            type: "list[float]"
            required: true
            description: See REQ-1118.
        - labels:
            type: "list[str]"
            required: true
            description: See REQ-1118.
        - right:
            type: bool
            default: false
            description: See REQ-1118.
        - missing:
            type: literal_value
            description: See REQ-1118.
"#),
    ("schema_expression_numeric.yaml", r#"version: "1.0"

# See REQ-1121.

expressions:
    compute: # See REQ-1119.
        - expr:
            type: numeric_expression
            required: true
            description: See REQ-1119.
    round_half_away_from_zero: # See REQ-1172.
        - source:
            type: variable
            required: true
            description: See REQ-1172.
        - digits:
            type: int
            required: true
            description: See REQ-1172.

numeric_expression:
    type: str
    min_length: 1
    description: See REQ-1120.
"#),
    ("schema_expression_odm.yaml", r#"version: "1.0"

# See REQ-1265.

expressions:
    odm: # See REQ-1265.
        type: [odm_item, odm_class]
        description: See REQ-1274.

odm_item:
    type: str
    pattern: '^[A-Za-z_][A-Za-z0-9_]*\.[!-~]+$'
    description: See REQ-1265.

odm_oid:
    type: str
    pattern: '^[!-~]+$'
    description: See REQ-1271.

odm_class:
    - item:
        type: odm_item
        required: true
        description: See REQ-1274.
    - event:
        type: [odm_oid, "list[odm_oid]"]
        description: See REQ-1274.
    - form:
        type: [odm_oid, "list[odm_oid]"]
        description: See REQ-1274.
    - item_group:
        type: [odm_oid, "list[odm_oid]"]
        description: See REQ-1274.
    - filter:
        type: predicate
        description: See REQ-1274.
"#),
    ("schema_expression_str.yaml", r#"version: "1.0"

expressions:
    str_pad: # See REQ-1261.
        - source:
            type: variable
            required: true
            description: See REQ-1261.
        - width:
            type: int
            required: true
            description: See REQ-1261.
    str_extract: # See REQ-1111.
        - source:
            type: variable
            required: true
            description: See REQ-1111.
        - pattern:
            type: regex
            required: true
            description: See REQ-1111.
        - group:
            type: int
            default: 0
            description: See REQ-1111.
        - missing:
            type: literal_value
            description: See REQ-1111.
        - no_match:
            type: literal_value
            description: See REQ-1111.
    str_contains: # See REQ-1243.
        - source:
            type: variable
            required: true
            description: See REQ-1243.
        - pattern:
            type: regex
            required: true
            description: See REQ-1243.
        - missing:
            type: literal_value
            description: See REQ-1243.
    str_concat: # See REQ-1112.
        - sources:
            type: "list[expression]"
            required: true
            description: See REQ-1112.
        - missing:
            type: literal_value
            description: See REQ-1112.
    str_template: # See REQ-1113.
        type: [string_template, str_template_class]
        description: See REQ-1113.
    str_case: # See REQ-1114.
        - source:
            type: variable
            required: true
            description: See REQ-1114.
        - to:
            type: str
            required: true
            values: [upper, lower, sentence, title]
            description: See REQ-1114.
        - missing:
            type: literal_value
            description: See REQ-1114.

string_template:
    type: str
    description: See REQ-1116.

str_template_class:
    - template:
        type: string_template
        required: true
        description: See REQ-1117.
    - missing:
        type: literal_value
        description: See REQ-1117.
"#),
    ("schema_expression_window.yaml", r#"version: "1.0"

# See REQ-1129.

window_selection:
    type: [identifier, window_spec]
    description: See REQ-1251.

window_spec:
    - group_by:
        type: "list[variable]"
        description: See REQ-1122.
    - order_by:
        type: "list[order_by_term]"
        description: See REQ-1122.
    - filter:
        type: predicate
        description: See REQ-1122.

expressions:
    row_number: # See REQ-1123.
        - window:
            type: window_selection
            description: See REQ-1123.
    rank: # See REQ-1124.
        - method:
            type: str
            default: competition
            values: [competition, dense]
            description: See REQ-1124.
        - window:
            type: window_selection
            description: See REQ-1124.
    row_value: # See REQ-1125.
        - source:
            type: variable
            required: true
            description: See REQ-1125.
        - offset:
            type: int
            required: true
            description: See REQ-1125.
        - window:
            type: window_selection
            description: See REQ-1125.
    previous_non_missing: # See REQ-1126.
        - source:
            type: variable
            required: true
            description: See REQ-1126.
        - window:
            type: window_selection
            description: See REQ-1126.
    locf: # See REQ-1239.
        - source:
            type: variable
            required: true
            description: See REQ-1239.
        - window:
            type: window_selection
            description: See REQ-1239.
    baseline_flag: # See REQ-1127.
        - date:
            type: variable
            required: true
            description: See REQ-1127.
        - reference_date:
            type: variable
            required: true
            description: See REQ-1127.
        - window:
            type: window_selection
            description: See REQ-1127.
"#),
    ("schema_function.yaml", r#"version: "1.0"

expressions:
    function: # See REQ-1085.
        - name:
            type: identifier
            required: true
            description: See REQ-1085.
        - args:
            type: "dict[identifier, function_arg]"
            default: {}
            description: See REQ-1085.

function_arg:
    type:
        - variable
        - int
        - float
        - bool
        - "null"
        - function_string_literal_class
        - function_date_literal_class
        - function_datetime_literal_class
    description: See REQ-1086.
"#),
    ("schema_metadata.yaml", r#"version: "1.0"

# See REQ-1148.

submission_dataset_class:
    - has_no_data:
        type: bool
        default: false
        description: See REQ-1296.
    - label:
        type: str
        required: true
        min_length: 1
        description: See REQ-1130.
    - class:
        type: dataset_class_name
        required: true
        description: See REQ-1130.
    - subclass:
        type: dataset_subclass_name
        required: false
        description: See REQ-1130.
    - structure:
        type: str
        required: true
        min_length: 1
        description: See REQ-1130.
    - repeating:
        type: bool
        required: true
        description: See REQ-1130.
    - reference_data:
        type: bool
        default: false
        description: See REQ-1130.
    - domain:
        type: identifier
        required: false
        description: See REQ-1130.
    - comment:
        type: submission_comment
        required: false
        description: See REQ-1130.

submission_column_class:
    - core:
        type: core_designation
        required: false
        description: See REQ-1131.
    - mandatory:
        type: bool
        required: false
        description: See REQ-1131.
    - role:
        type: str
        required: false
        min_length: 1
        description: See REQ-1131.
    - data_type:
        type: define_data_type
        required: false
        description: See REQ-1131.
    - length:
        type: int
        required: false
        description: See REQ-1131.
    - significant_digits:
        type: int
        required: false
        description: See REQ-1131.
    - display_format:
        type: str
        required: false
        min_length: 1
        description: See REQ-1131.
    - codelist:
        type: identifier
        required: false
        description: See REQ-1131.
    - inventory_vocabulary:
        type: bool
        required: false
        description: See REQ-1156.
    - origin:
        type: submission_origin_class
        required: false
        description: See REQ-1131.
    - method:
        type: submission_method
        required: false
        description: See REQ-1131.
    - comment:
        type: submission_comment
        required: false
        description: See REQ-1131.

# See REQ-1157.

submission_origin_class:
    - type:
        type: origin_type
        required: true
        description: See REQ-1132.
    - source:
        type: origin_source
        required: false
        description: See REQ-1132.
    - description:
        type: str
        required: false
        min_length: 1
        description: See REQ-1132.
    - documents:
        type: "list[document_reference]"
        required: false
        description: See REQ-1132.

submission_method_class:
    - name:
        type: str
        required: false
        min_length: 1
        description: See REQ-1133.
    - type:
        type: method_type
        default: Computation
        description: See REQ-1133.
    - description:
        type: str
        required: true
        min_length: 1
        description: See REQ-1133.
    - expression:
        type: formal_expression_class
        required: false
        description: See REQ-1133.
    - documents:
        type: "list[document_reference]"
        required: false
        description: See REQ-1133.

submission_comment_class:
    - text:
        type: str
        required: true
        min_length: 1
        description: See REQ-1134.
    - documents:
        type: "list[document_reference]"
        required: false
        description: See REQ-1134.

formal_expression_class:
    - context:
        type: str
        required: true
        min_length: 1
        description: See REQ-1135.
    - code:
        type: str
        required: true
        min_length: 1
        description: See REQ-1135.

document_reference_class:
    - document:
        type: identifier
        required: true
        description: See REQ-1136.
    - pages:
        type: page_reference_class
        required: false
        description: See REQ-1136.

page_reference_class:
    - type:
        type: str
        required: true
        values: [PhysicalRef, NamedDestination]
        description: See REQ-1137.
    - refs:
        type: str
        required: true
        min_length: 1
        description: See REQ-1137.
    - title:
        type: str
        required: false
        min_length: 1
        description: See REQ-1137.

submission_comment:
    type: [str, submission_comment_class]
    description: See REQ-1138.

submission_method:
    type: [str, submission_method_class]
    description: See REQ-1139.

document_reference:
    type: [identifier, document_reference_class]
    description: See REQ-1140.

core_designation:
    type: str
    values: [Req, Exp, Perm, Cond]
    description: See REQ-1141.

origin_type:
    type: str
    values: [Assigned, Collected, Derived, Not Available, Other, Predecessor,
        Protocol]
    description: See REQ-1142.

origin_source:
    type: str
    values: [Investigator, Sponsor, Subject, Vendor]
    description: See REQ-1143.

method_type:
    type: str
    values: [Computation, Imputation]
    description: See REQ-1144.

define_data_type:
    type: str
    values: [text, integer, float, date, datetime, time, partialDate,
        partialTime, partialDatetime, incompleteDate, incompleteTime,
        incompleteDatetime, durationDatetime, intervalDatetime, URI]
    description: See REQ-1145.

dataset_class_name:
    type: str
    values: [ADAM OTHER, BASIC DATA STRUCTURE, DEVICE LEVEL ANALYSIS DATASET,
        EVENTS, FINDINGS, FINDINGS ABOUT, INTERVENTIONS,
        MEDICAL DEVICE BASIC DATA STRUCTURE,
        MEDICAL DEVICE OCCURRENCE DATA STRUCTURE, OCCURRENCE DATA STRUCTURE,
        REFERENCE DATA STRUCTURE, RELATIONSHIP, SPECIAL PURPOSE,
        STUDY REFERENCE, SUBJECT LEVEL ANALYSIS DATASET, TRIAL DESIGN]
    description: See REQ-1146.

dataset_subclass_name:
    type: str
    values: [ADVERSE EVENT, MEDICAL DEVICE TIME-TO-EVENT,
        NON-COMPARTMENTAL ANALYSIS, POPULATION PHARMACOKINETIC ANALYSIS,
        TIME-TO-EVENT]
    description: See REQ-1147.
"#),
    ("schema_shared.yaml", r#"version: "1.0"

# See REQ-1150.

column_type:
    type: str
    values: [str, int, float, date, datetime]

literal_value:
    type: [str, int, float, bool, "null"]
    description: See REQ-1149.

path:
    type: str
    min_length: 1

project_path:
    type: str
    min_length: 1
    description: See REQ-1151.

identifier:
    type: str
    pattern: '^[A-Za-z_][A-Za-z0-9_]*$'
    description: See REQ-1046.


function_param_type:
    type: str
    values: [str, int, float, bool, date, datetime]

function_string_literal_class:
    - literal: {type: str, required: true}

function_date_literal_class:
    - date: {type: str, required: true}

function_datetime_literal_class:
    - datetime: {type: str, required: true}

function_value:
    type:
        - literal_value
        - function_date_literal_class
        - function_datetime_literal_class

"#),
    ("schema_verification.yaml", r#"version: "1.0"

column_verification:
    registry: column_verifications

column_verifications:
    not_missing:
        - id: {type: verification_id, required: false}
        - severity: {type: verification_severity, required: false, default: error}
    allowed_values:
        - id: {type: verification_id, required: false}
        - values: {type: "list[literal_value]", required: true}
        - severity: {type: verification_severity, required: false, default: error}
    range:
        - id: {type: verification_id, required: false}
        - min: {type: float, required: false}
        - max: {type: float, required: false}
        - severity: {type: verification_severity, required: false, default: error}
    max_length:
        - id: {type: verification_id, required: false}
        - max: {type: int, required: true}
        - severity: {type: verification_severity, required: false, default: error}
    matches:
        - id: {type: verification_id, required: false}
        - pattern: {type: regex, required: true}
        - severity: {type: verification_severity, required: false, default: error}

dataset_verification:
    registry: dataset_verifications

dataset_verifications:
    unique:
        type: ["list[variable]", dataset_unique_arguments]
    all_or_none:
        - id: {type: verification_id, required: false}
        - columns: {type: "list[variable]", required: true}
        - severity: {type: verification_severity, required: false, default: error}
    assert:
        - id: {type: verification_id, required: false}
        - when:
            type: predicate
            required: false
            description: See REQ-0383.
        - require: {type: predicate, required: true}
        - severity: {type: verification_severity, required: false, default: error}
    row_count: # See REQ-1152.
        - id: {type: verification_id, required: false}
        - group_by: {type: "list[variable]", required: false}
        - filter: {type: predicate, required: false}
        - when:
            type: predicate
            required: false
            description: See REQ-1154.
        - min: {type: int, required: false}
        - max: {type: int, required: false}
        - min_fraction: {type: float, required: false}
        - max_fraction: {type: float, required: false}
        - severity: {type: verification_severity, required: false, default: error}

intermediate_verification:
    registry: intermediate_verifications

intermediate_verifications:
    unique:
        type: ["list[variable]", intermediate_unique_arguments]

dataset_unique_arguments:
    - id: {type: verification_id, required: false}
    - columns: {type: "list[variable]", required: true}
    - severity: {type: verification_severity, required: false, default: error}

intermediate_unique_arguments:
    - id: {type: verification_id, required: false}
    - columns: {type: "list[variable]", required: true}

verification_id:
    type: str
    min_length: 1

verification_severity:
    type: str
    values: [error, warning]
"#),
];
#[rustfmt::skip]
pub(super) const ENVIRONMENT_MODULES: &[(&str, &str)] = &[
    ("schema_environment.yaml", r#"version: '1.0'
includes:
- schema_shared.yaml
environment_class:
- schema_version:
    type: str
    required: true
    description: See REQ-1080.
- language:
    type: str
    values:
    - python
    - r
    description: See REQ-1080.
- lock:
    type: path
    description: See REQ-1080.
- functions:
    type: dict[identifier, function_definition]
    description: See REQ-1080.
- codelists:
    type: list[codelist_source]
    description: See REQ-1080.
- study:
    type: study_class
    description: See REQ-1080.
- sdtm:
    type: submission_section_class
    description: See REQ-1080.
- adam:
    type: submission_section_class
    description: See REQ-1080.
- send:
    type: submission_section_class
    description: See REQ-1080.
function_definition:
  type:
  - path
  - function_definition_class
  description: See REQ-1083.
function_definition_class:
- function:
    type: qualified_callable
    required: true
    description: See REQ-1083.
- description:
    type: str
    required: true
    min_length: 1
    description: See REQ-1083.
- params:
    type: list[function_parameter_class]
    required: true
    description: See REQ-1083.
- returns:
    type: column_type
    required: true
    description: See REQ-1083.
- may_return_missing:
    type: bool
    default: false
    description: See REQ-1083.
- comparison_decimals:
    type: int
    default: 4
    description: See REQ-1083.
- tests:
    type: list[function_test_class]
    required: true
    description: See REQ-1083.
function_parameter_class:
- name:
    type: identifier
    required: true
    description: See REQ-1083.
- type:
    type: function_param_type
    required: true
    description: See REQ-1083.
- required:
    type: bool
    default: true
    description: See REQ-1083.
- default:
    type: function_value
    description: See REQ-1083.
- accepts_missing:
    type: bool
    default: false
    description: See REQ-1083.
qualified_callable:
  type: str
  min_length: 1
  description: See REQ-0669.
function_case_id:
  type: str
  pattern: ^[a-z][a-z0-9-]*$
  description: See REQ-1083.
function_coverage:
  type: str
  pattern: ^(normal|boundary|nullable-output|numeric-comparison|(default|accepted-missing|short-circuit-missing|boolean-true|boolean-false):[A-Za-z_][A-Za-z0-9_]*)$
  description: See REQ-1083.
function_test_class:
- id:
    type: function_case_id
    required: true
    description: See REQ-1083.
- covers:
    type: list[function_coverage]
    required: true
    description: See REQ-1083.
- args:
    type: dict[identifier, function_value]
    required: true
    description: See REQ-1083.
- result:
    type: function_value
    required: true
    description: See REQ-1083.
codelist_source:
  type:
  - path
  - codelist_source_class
  description: See REQ-0928.
codelist_source_class:
- standard:
    type: terminology_standard_class
    description: See REQ-0928.
- codelists:
    type: list[codelist_class]
    required: true
    description: See REQ-0928.
terminology_standard_class:
- name:
    type: str
    required: true
    min_length: 1
    description: See REQ-0928.
- publishing_set:
    type: str
    required: true
    values:
    - ADaM
    - CDASH
    - DEFINE-XML
    - SDTM
    - SEND
    description: See REQ-0928.
- version:
    type: str
    required: true
    min_length: 1
    description: See REQ-0928.
study_class:
- id:
    type: define_id
    required: true
    description: See REQ-1062.
- name:
    type: str
    required: true
    min_length: 1
    description: See REQ-1062.
- description:
    type: str
    required: true
    min_length: 1
    description: See REQ-1062.
- protocol_name:
    type: str
    required: true
    min_length: 1
    description: See REQ-1062.
metadata_version_class:
- id:
    type: define_id
    required: true
    description: See REQ-1063.
- name:
    type: str
    required: true
    min_length: 1
    description: See REQ-1063.
- description:
    type: str
    required: false
    min_length: 1
    description: See REQ-1063.
codelist_class:
- id:
    type: identifier
    required: true
    description: See REQ-1077.
- name:
    type: str
    required: true
    min_length: 1
    description: See REQ-1077.
- data_type:
    type: str
    default: text
    values:
    - text
    - integer
    - float
    description: See REQ-1077.
- extensible:
    type: bool
    default: false
    description: See REQ-1077.
- alias:
    type: str
    required: false
    min_length: 1
    description: See REQ-1077.
- format_name:
    type: str
    required: false
    min_length: 1
    description: See REQ-1077.
- items:
    type: list[codelist_item_class]
    required: false
    description: See REQ-1077.
- external:
    type: external_codelist_class
    required: false
    description: See REQ-1077.
codelist_item_class:
- value:
    type: literal_value
    required: true
    description: See REQ-1078.
- decode:
    type: str
    required: false
    min_length: 1
    description: See REQ-1078.
- rank:
    type: int
    required: false
    description: See REQ-1078.
- alias:
    type: str
    required: false
    min_length: 1
    description: See REQ-1078.
- extended:
    type: bool
    default: false
    description: See REQ-1078.
external_codelist_class:
- dictionary:
    type: str
    required: true
    min_length: 1
    description: See REQ-1079.
- version:
    type: str
    required: true
    min_length: 1
    description: See REQ-1079.
- href:
    type: str
    required: false
    min_length: 1
    description: See REQ-1079.
define_id:
  type: str
  pattern: ^[A-Za-z_][A-Za-z0-9_.-]*$
  description: See REQ-1068.
relative_href:
  type: str
  pattern: ^(?!/)(?!.*(^|/)\.\.(/|$))[^\\]+$
  description: See REQ-1070.
language_tag:
  type: str
  pattern: ^[A-Za-z]{2,3}(-[A-Za-z0-9]{1,8})*$
  description: See REQ-1073.
standard_name:
  type: str
  values:
  - ADaMIG
  - ADaMIG-MD
  - BIMO
  - CDISC/NCI
  - SDTMIG
  - SDTMIG-AP
  - SDTMIG-MD
  - SENDIG
  - SENDIG-AR
  - SENDIG-DART
  - SENDIG-GENETOX
  description: See REQ-1074.
submission_section_class:
- standard:
    type: implementation_guide_class
    required: true
- specs:
    type: list[path]
    required: true
- define:
    type: path
    required: true
- documents:
    type: list[document_class]
- dataset_json:
    type: bool
    default: false
- context:
    type: str
    default: Submission
    values:
    - Submission
    - Other
- xml_lang:
    type: language_tag
    default: en
- file_oid:
    type: define_id
- metadata_version:
    type: metadata_version_class
- originator:
    type: str
    min_length: 1
- stylesheet:
    type: relative_href
implementation_guide_class:
- name:
    type: standard_name
    required: true
- version:
    type: str
    required: true
    min_length: 1
- status:
    type: str
    required: true
    values:
    - Draft
    - Final
document_class:
- id:
    type: identifier
    required: true
    description: See REQ-1065.
- kind:
    type: str
    required: true
    values:
    - annotated_crf
    - supplemental
    - other
    description: See REQ-1065.
- link:
    type: relative_href
    required: true
    description: See REQ-1065.
- title:
    type: str
    required: true
    min_length: 1
    description: See REQ-1065.
"#),
    ("schema_shared.yaml", r#"version: "1.0"

# See REQ-1150.

column_type:
    type: str
    values: [str, int, float, date, datetime]

literal_value:
    type: [str, int, float, bool, "null"]
    description: See REQ-1149.

path:
    type: str
    min_length: 1

project_path:
    type: str
    min_length: 1
    description: See REQ-1151.

identifier:
    type: str
    pattern: '^[A-Za-z_][A-Za-z0-9_]*$'
    description: See REQ-1046.


function_param_type:
    type: str
    values: [str, int, float, bool, date, datetime]

function_string_literal_class:
    - literal: {type: str, required: true}

function_date_literal_class:
    - date: {type: str, required: true}

function_datetime_literal_class:
    - datetime: {type: str, required: true}

function_value:
    type:
        - literal_value
        - function_date_literal_class
        - function_datetime_literal_class

"#),
];
